import type { CSSProperties } from 'react';
import { createHash } from 'node:crypto';
import { menuMessages,uiMessages,type Language,type MenuKey } from '@bigant/i18n';
import type { PublicMenu,PublicMenuItem } from '@bigant/types';
import { slugParam } from '@bigant/types';
export const dynamic='force-dynamic';
export default async function MenuPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{lang?:string}>}){
 const {slug}=await params;const query=await searchParams;let language:Language=query.lang==='en'?'en':'it';let menu:PublicMenu|null=null;
 if(slugParam.safeParse({slug}).success){try{const response=await fetch(`${process.env.API_INTERNAL_URL??'http://127.0.0.1:3001'}/public/${slug}/menu${query.lang==='en'||query.lang==='it'?`?lang=${query.lang}`:''}`,{cache:'no-store',signal:AbortSignal.timeout(5000)});if(response.ok){menu=await response.json() as PublicMenu;language=menu.language;}}catch{/* Il menu offre un errore recuperabile senza esporre dettagli del server. */}}
 const t=menuMessages[language],ui=uiMessages[language];
 if(!menu)return <main className="menu-public" lang={language}><div className="panel menu-empty"><h1>{t.menu}</h1><p role="alert">{t.menuUnavailable}</p><a className="button primary" href={`?lang=${language}`}>{ui.retry}</a></div></main>;
 const color=menu.settings.menu_primary_color;const rgb=[1,3,5].map(n=>parseInt(color.slice(n,n+2),16)/255).map(v=>v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4);const luminance=rgb[0]!*0.2126+rgb[1]!*0.7152+rgb[2]!*0.0722;const style={'--menu-color':color,'--menu-ink':luminance>.22?color:'#f4f1ed','--menu-on-color':luminance>.179?'#111111':'#ffffff'} as CSSProperties;
 const fingerprint=createHash('sha256').update(JSON.stringify(menu)).digest('hex');
 // Solo questo piccolo script aggiorna un menu già aperto; nessuna dipendenza
 // dal router client per mostrare il contenuto iniziale.
 const liveScript=`(()=>{let busy=false;const check=async()=>{if(busy||document.visibilityState!=='visible')return;busy=true;try{const response=await fetch(${JSON.stringify('/api/public/'+slug+'/menu?lang='+language)},{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)return;const bytes=new TextEncoder().encode(JSON.stringify(await response.json()));const digest=await crypto.subtle.digest('SHA-256',bytes);const hash=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join('');if(hash!==${JSON.stringify(fingerprint)})location.reload();}catch{}finally{busy=false;}};setInterval(check,30000);document.addEventListener('visibilitychange',check);})();`;
 const featured=menu.categories.flatMap(c=>c.items.filter(i=>i.is_featured));const count=menu.categories.reduce((sum,c)=>sum+c.items.length,0);
 return <main className={`menu-public menu-template-${menu.settings.menu_template}`} lang={language} style={style}><header className="menu-header"><a className="menu-venue" href={`/r/${slug}/menu?lang=${language}`}>{menu.tenant.name}</a><nav className="language-switch" aria-label={ui.language}>{(['it','en'] as const).map(l=><a key={l} href={`?lang=${l}`} hrefLang={l} className={language===l?'selected':''} aria-current={language===l?'page':undefined}>{uiMessages[l][l]}</a>)}</nav></header>{menu.settings.menu_cover_url&&<img className="menu-cover" src={menu.settings.menu_cover_url} srcSet={[320,640,960].map(w=>`${menu.settings.menu_cover_url!.replace('-640.webp',`-${w}.webp`)} ${w}w`).join(', ')} sizes="(max-width: 800px) 100vw, 744px" width={960} height={720} alt={menu.tenant.name} fetchPriority="high"/>}<section className="menu-intro"><span className="eyebrow accent">{t.menuEyebrow}</span><h1>{t.menu}</h1><p>{t.menuIntro}</p>{menu.tenant.address&&<p className="small muted">{menu.tenant.address}</p>}</section>{count>0?<><nav className="menu-jumps" aria-label={t.menuCategories}>{featured.length>0&&<a href="#featured">{t.featured}</a>}{menu.categories.filter(c=>c.items.some(i=>!i.is_featured)).map(c=><a href={`#category-${c.id}`} key={c.id}>{c.name}</a>)}</nav>{featured.length>0&&<section id="featured" className="menu-section"><div className="menu-section-heading"><span aria-hidden="true">✳</span><h2>{t.featured}</h2></div>{featured.map((item,n)=><Dish key={item.id} item={item} language={language} first={n===0}/>)}</section>}{menu.categories.map(c=>c.items.some(i=>!i.is_featured)&&<section id={`category-${c.id}`} className="menu-section" key={c.id}><div className="menu-section-heading"><h2>{c.name}</h2><span className="muted">{String(c.items.filter(i=>!i.is_featured).length).padStart(2,'0')}</span></div>{c.items.filter(i=>!i.is_featured).map(item=><Dish key={item.id} item={item} language={language}/>)}</section>)}<footer className="menu-footer"><h2>{t.allergens}</h2><p>{t.allergenHint}</p></footer></>:<div className="panel menu-empty"><p>{t.emptyMenu}</p></div>}<a href={`/r/${slug}/prenota`} className="button primary wide">{ui.book} →</a><script dangerouslySetInnerHTML={{__html:liveScript}}/></main>;
}
function Dish({item,language,first=false}:{item:PublicMenuItem;language:Language;first?:boolean}){
 const t=menuMessages[language];const label=(prefix:string,code:string)=>t[`${prefix}_${code}` as MenuKey]??code;
 return <article className={`menu-dish${item.is_available?'':' sold-out'}`} data-dish={item.id}>{item.image_url&&<img className="menu-photo" src={item.image_url} srcSet={[320,640,960].map(w=>`${item.image_url!.replace('-640.webp',`-${w}.webp`)} ${w}w`).join(', ')} sizes="(max-width: 450px) 88px, 128px" width={128} height={96} alt={item.name} loading={first?'eager':'lazy'} decoding="async"/>}<div className="menu-dish-copy"><div className="menu-dish-title"><h3>{item.name}</h3><strong>{new Intl.NumberFormat(language==='it'?'it-IT':'en-IE',{style:'currency',currency:'EUR'}).format(item.price_cents/100)}</strong></div>{item.description&&<p className="menu-description">{item.description}</p>}{!item.is_available&&<span className="sold-out-label">{t.soldOut}</span>}{item.dietary.length>0&&<ul className="dietary-tags" aria-label={t.dietary}>{item.dietary.map(code=><li key={code}>{label('diet',code)}</li>)}</ul>}{item.allergens.length>0&&<p className="allergen-line"><span>{t.allergens}: </span>{item.allergens.map(code=>label('allergen',code)).join(', ')}</p>}</div></article>;
}
