packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - argon2
  - esbuild
  - embedded-postgres
  - '@embedded-postgres/darwin-x64'
  - '@embedded-postgres/darwin-arm64'
  - '@embedded-postgres/linux-x64'
