import {test,expect} from '@playwright/test';

test('console agenzia: cliente, piano, servizi, attivazione, sospensione e registro',async({page,context},testInfo)=>{
 await page.goto('/admin');
 await page.getByLabel('Email',{exact:true}).fill('e2e-admin@bigant.test');
 await page.getByLabel('Password',{exact:true}).fill('console-e2e-password-2026');
 await page.getByRole('button',{name:'Accedi alla console',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Panoramica',exact:true})).toBeVisible();
 await expect(page.getByText('Canoni mensili concordati',{exact:true})).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:testInfo.outputPath('console-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Nuovo cliente'}).click();
 const modal=page.getByRole('dialog');
 await modal.getByLabel('Nome del locale',{exact:true}).fill('Cliente E2E Console');
 await modal.getByLabel('Indirizzo del locale',{exact:false}).fill('console-e2e-venue');
 await modal.getByLabel('Nome del titolare',{exact:true}).fill('Titolare E2E');
 await modal.getByLabel('Email del titolare',{exact:true}).fill('owner@console-e2e.test');
 await modal.getByRole('button',{name:'Crea cliente',exact:true}).click();
 await expect(modal.getByRole('heading',{name:'Link di attivazione pronto'})).toBeVisible();
 const activation=await modal.getByLabel('Genera link di accesso',{exact:true}).inputValue();
 expect(activation).toMatch(/\/attiva-accesso#[a-f0-9]{64}$/);
 await modal.getByRole('button',{name:'Chiudi',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Cliente E2E Console',exact:true})).toBeVisible();
 await page.locator('.console-tabs').getByRole('button',{name:'Piano e scadenze'}).click();
 await page.getByRole('combobox',{name:'Piano',exact:true}).selectOption('pro');
 await page.getByLabel('Canone mensile (€)',{exact:true}).fill('89,90');
 await page.getByLabel('Note interne',{exact:true}).fill('Cliente pilota E2E');
 await page.getByRole('button',{name:'Salva modifiche',exact:true}).click();
 await expect(page.getByLabel('Canone mensile (€)',{exact:true})).toHaveValue('89.90');
 await page.locator('.console-tabs').getByRole('button',{name:'Servizi',exact:true}).click();
 await expect(page.getByLabel('Conferma automatica',{exact:true})).toBeChecked();
 await expect(page.getByLabel('Assegnazione automatica del tavolo',{exact:true})).toBeChecked();
 await page.getByLabel('Capienza totale',{exact:true}).fill('24');
 await page.getByRole('button',{name:'Salva modifiche',exact:true}).click();
 await expect(page.getByLabel('Capienza totale',{exact:true})).toHaveValue('24');
 const owner=await context.newPage();await owner.goto(activation);
 await expect(owner).toHaveURL(/\/attiva-accesso$/);
 await owner.getByLabel('Nuova password',{exact:true}).fill('owner-e2e-password-2026');
 await owner.getByLabel('Ripeti la password',{exact:true}).fill('owner-e2e-password-2026');
 await owner.getByRole('button',{name:'Imposta password',exact:true}).click();
 await expect(owner.getByRole('link',{name:'Accesso gestore'})).toBeVisible();
 await owner.getByRole('link',{name:'Accesso gestore'}).click();
 await owner.getByLabel('Email',{exact:true}).fill('owner@console-e2e.test');
 await owner.getByLabel('Password',{exact:true}).fill('owner-e2e-password-2026');
 await owner.getByRole('button',{name:/Accedi/}).click();
 await expect(owner.locator('.staff-shell')).toBeVisible();
 await page.getByRole('button',{name:'Cambia stato',exact:true}).click();
 await modal.getByRole('combobox',{name:'Stato',exact:true}).selectOption('suspended');
 await modal.getByLabel('Motivo della modifica',{exact:false}).fill('Pausa richiesta dal cliente');
 await modal.getByRole('button',{name:'Conferma',exact:true}).click();
 await modal.getByRole('button',{name:'Annulla modifica',exact:true}).click();
 await expect(page.locator('.console-detail-heading .console-badge')).toHaveText('Attivo');
 await page.getByRole('button',{name:'Cambia stato',exact:true}).click();
 await modal.getByRole('combobox',{name:'Stato',exact:true}).selectOption('suspended');
 await modal.getByLabel('Motivo della modifica',{exact:false}).fill('Pausa richiesta dal cliente');
 await modal.getByRole('button',{name:'Conferma',exact:true}).click();
 await expect(modal).not.toBeVisible({timeout:15000});
 await expect(page.locator('.console-detail-heading .console-badge')).toHaveText('Sospeso');
 const blocked=await page.request.get('/api/public/console-e2e-venue');expect(blocked.status()).toBe(404);
 await owner.reload();await expect(owner.getByRole('alert').filter({hasText:'Risorsa non trovata'})).toBeVisible();await expect(owner.locator('.staff-shell')).toHaveCount(0);await owner.close();
 await page.locator('.console-tabs').getByRole('button',{name:'Registro attività',exact:true}).click();
 await expect(page.getByText('Stato cliente modificato',{exact:true})).toBeVisible();
 await expect(page.getByText('Pausa richiesta dal cliente',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Tutti i clienti',exact:false}).click();
 await page.getByLabel('Cerca un locale',{exact:true}).fill('Cliente E2E');
 await page.getByRole('button',{name:'Cerca',exact:true}).click();
 await expect(page.locator('.console-client')).toHaveCount(1);
 await page.setViewportSize({width:375,height:812});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:testInfo.outputPath('console-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'EN',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Clients',exact:true})).toBeVisible();
 await page.getByRole('button',{name:/Sign out/}).click();
 await expect(page.getByRole('button',{name:'Sign in to the console',exact:true})).toBeVisible();
});
