import { test,expect,chromium } from '@playwright/test';
import sharp from '../../apps/api/node_modules/sharp/lib/index.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir,writeFile } from 'node:fs/promises';
test('menu mobile: categoria, piatto con foto, quattro stili, lingua, esaurito e occhio',async({page,context})=>{
 test.setTimeout(240000);
 await page.goto('/staff');await page.getByLabel('Password',{exact:true}).fill('bigant2026');await page.getByRole('button',{name:/Accedi al pannello/}).click();await page.getByRole('button',{name:'Menu',exact:true}).click();
 await page.getByRole('button',{name:'Nuova categoria',exact:false}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Nome in italiano').fill('Specialità browser');await dialog.getByLabel('Nome in inglese').fill('Browser specials');await dialog.getByRole('button',{name:'Salva modifiche'}).click();
 const category=page.locator('.menu-admin-category').filter({has:page.getByRole('heading',{name:'Specialità browser',exact:true})});await category.getByRole('button',{name:'Nuovo piatto',exact:false}).click();dialog=page.getByRole('dialog');
 await dialog.getByLabel('Nome in italiano').fill('Risotto agli agrumi');await dialog.getByLabel('Nome in inglese').fill('Citrus risotto');await dialog.getByLabel('Descrizione in italiano').fill('Riso, limone e un tocco di rosmarino.');await dialog.getByLabel('Descrizione in inglese').fill('Rice, lemon and a touch of rosemary.');await dialog.getByLabel('Prezzo (€)').fill('12,50');await dialog.getByLabel('Latte',{exact:true}).check();await dialog.getByLabel('Vegetariano',{exact:true}).check();await dialog.getByLabel('Metti in evidenza').check();
 const image=await sharp({create:{width:800,height:600,channels:3,background:'#a56330'}}).png().toBuffer();await dialog.getByLabel('Foto del piatto',{exact:true}).setInputFiles({name:'piatto.png',mimeType:'image/png',buffer:image});await dialog.getByRole('button',{name:'Salva modifiche'}).click();await expect(dialog).not.toBeVisible();
 await page.locator('.menu-appearance summary').click();const appearance=page.locator('.menu-appearance');await appearance.getByLabel('Immagine di copertina',{exact:true}).setInputFiles({name:'copertina.png',mimeType:'image/png',buffer:image});await appearance.getByRole('button',{name:'Salva modifiche'}).click();await expect(appearance.getByRole('status')).toContainText('Modifiche salvate');await appearance.getByLabel('Immagine di copertina',{exact:true}).setInputFiles([]);
 const guest=await context.newPage();await guest.goto('/r/trattoria-santa-lucia/menu');await expect(guest.getByRole('heading',{name:'Risotto agli agrumi',exact:true})).toBeVisible();const dish=guest.locator('.menu-dish').filter({hasText:'Risotto agli agrumi'});await expect(dish).toContainText('12,50');await expect(dish).toContainText('Latte');await expect(dish.locator('img')).toHaveAttribute('srcset',/320w.*640w.*960w/);expect(await dish.locator('img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);
 await guest.getByRole('link',{name:'EN',exact:true}).click();await expect(guest.getByRole('heading',{name:'Citrus risotto',exact:true})).toBeVisible();await expect(guest.getByText('Rice, lemon and a touch of rosemary.')).toBeVisible();await expect(guest.getByRole('heading',{name:'Risotto agli agrumi',exact:true})).toHaveCount(0);await guest.getByRole('link',{name:'IT',exact:true}).click();
 await mkdir('test-results/visual',{recursive:true});
 for(const [label,key] of [['Essenziale','essential'],['Pop','pop'],['Elegante','elegant'],['Pub','pub']] as const){await appearance.getByRole('radio',{name:new RegExp(label)}).check();await appearance.getByRole('button',{name:'Salva modifiche'}).click();await expect(appearance.getByRole('status')).toContainText('Modifiche salvate');await guest.reload();await expect(guest.locator('main')).toHaveClass(new RegExp(`menu-template-${key}`));await expect(guest.locator('main')).toBeVisible();expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await guest.screenshot({path:`test-results/visual/menu-${key}-375.png`,fullPage:false});}
 const staffDish=category.locator('.menu-admin-dish').filter({hasText:'Risotto agli agrumi'});await staffDish.getByRole('button',{name:'Risotto agli agrumi: Disponibile',exact:true}).click();await expect(staffDish.getByRole('button',{name:'Risotto agli agrumi: Esaurito per oggi',exact:true})).toBeVisible();await guest.reload();await expect(dish).toHaveClass(/sold-out/);await expect(dish).toContainText('Esaurito per oggi');
 await staffDish.getByRole('button',{name:'Nascondi dal menu Risotto agli agrumi',exact:true}).click();await expect(staffDish).toContainText('Nascosto dal pubblico');
 // Una pagina già aperta riceve la visibilità aggiornata senza ricarica manuale.
 await guest.bringToFront();await expect(guest.getByRole('heading',{name:'Risotto agli agrumi',exact:true})).toHaveCount(0,{timeout:40000});
 const response=await guest.request.get('/api/public/trattoria-santa-lucia/menu');expect(response.status()).toBe(200);expect(await response.text()).not.toContain('Risotto agli agrumi');
 await staffDish.getByRole('button',{name:'Mostra nel menu Risotto agli agrumi',exact:true}).click();await expect(staffDish.getByRole('button',{name:'Nascondi dal menu Risotto agli agrumi',exact:true})).toBeVisible();await guest.reload();await expect(dish).toContainText('Esaurito per oggi');
 await guest.goto('/r/lido-miseno/menu');await expect(guest.getByRole('link',{name:'Lido Miseno',exact:true})).toBeVisible();await expect(guest.getByRole('heading',{name:'Risotto agli agrumi',exact:true})).toHaveCount(0);
 await writeFile('test-results/menu-response.html',await (await guest.request.get('/r/trattoria-santa-lucia/menu')).text());
 const audit=await promisify(execFile)(process.execPath,['scripts/menu-performance.mjs','http://localhost:3100/r/trattoria-santa-lucia/menu'],{timeout:160000,env:{...process.env,CHROME_PATH:process.env.CHROME_PATH??(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':chromium.executablePath())}});expect(audit.stdout).toContain('Lighthouse mobile:');
 await guest.close();
});
