import { expect,test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
test('recensioni a 375px: scelte equivalenti, privato, card, limite e gestione staff',async({page,context})=>{
 await page.goto('/r/trattoria-santa-lucia/staff?view=cards');await page.getByLabel('Password',{exact:true}).fill('bigant2026');await page.getByRole('button',{name:/Accedi al pannello/}).click();await expect(page.getByRole('heading',{name:'Un tocco, una voce.'})).toBeVisible();
 await page.getByRole('button',{name:'Nuova card',exact:false}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Nome della card').fill('Card browser recensioni');await dialog.getByRole('button',{name:'Salva modifiche'}).click();await expect(dialog).not.toBeVisible();
 const card=page.locator('.nfc-card').filter({has:page.getByRole('heading',{name:'Card browser recensioni',exact:true})});const url=await card.getByLabel('Link della card').inputValue();expect(url).toMatch(/\/r\/trattoria-santa-lucia\/feedback\?card=[a-f0-9]{64}$/);
 const guest=await context.newPage();await guest.goto(url);await expect(guest.locator('.feedback-option')).toHaveCount(2);await expect(guest.getByRole('radio')).toHaveCount(0);
 const styles=await guest.locator('.feedback-option').evaluateAll(nodes=>nodes.map(node=>{const style=getComputedStyle(node);const rect=node.getBoundingClientRect();return {width:rect.width,height:rect.height,fontWeight:style.fontWeight,background:style.backgroundColor,color:style.color};}));expect(styles[0]).toEqual(styles[1]);
 expect(await guest.locator('main').innerText()).not.toMatch(/positiva|5\s+stelle|sconto|omaggio/i);await expect(guest.getByText('Puoi farlo con calma più tardi.')).toBeVisible();await expect(guest.getByRole('button',{name:'Copia questo link'})).toBeVisible();
 expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('test-results/visual',{recursive:true});await guest.screenshot({path:'test-results/visual/feedback-scelte-375.png',fullPage:true});
 await guest.getByRole('button',{name:'Scrivi a noi in privato'}).click();await guest.getByRole('radio',{name:'Valutazione 1',exact:true}).check();await expect(guest.getByRole('button',{name:'Lascia una recensione su Google'})).toBeEnabled();await guest.getByLabel('Il tuo messaggio (facoltativo)').fill('Messaggio privato del browser.');await guest.getByRole('button',{name:'Invia il feedback',exact:false}).click();await expect(guest.getByRole('heading',{name:'Grazie per averci scritto.'})).toBeVisible();
 await guest.reload();await guest.getByRole('button',{name:'Lascia una recensione su Google'}).click();await expect(guest.getByRole('alert').filter({hasText:'Questa card'})).toContainText('ultimi dieci minuti');await expect(guest).toHaveURL(url);
 await page.getByRole('button',{name:'Recensioni',exact:false}).click();const review=page.locator('.review-row').filter({hasText:'Messaggio privato del browser.'});await expect(review).toBeVisible();await expect(review).toContainText('1');await review.getByRole('button',{name:'Nota interna'}).click();await page.getByRole('dialog').getByLabel('Nota interna').fill('Nota riservata del browser.');await page.getByRole('dialog').getByRole('button',{name:'Salva modifiche'}).click();await expect(review).toContainText('Nota riservata del browser.');await review.getByRole('button',{name:'Segna come letto'}).click();await expect(review).toHaveCount(0);
 await page.locator('.review-filters select').nth(1).selectOption('seen');await expect(review).toContainText('Letto');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/visual/recensioni-staff-375.png',fullPage:true});
 await guest.goto('/r/trattoria-santa-lucia/feedback');await expect(guest.locator('main')).not.toContainText('Nota riservata del browser.');await guest.getByRole('button',{name:'Lascia una recensione su Google'}).click();await expect(guest.getByRole('heading',{name:'Collegamento Google registrato'})).toBeVisible();
 await guest.goto('/r/lido-miseno/feedback');await expect(guest.getByRole('button',{name:'Lascia una recensione su Google'})).toHaveCount(0);await expect(guest.getByRole('button',{name:'Scrivi a noi in privato'})).toBeVisible();await guest.getByRole('button',{name:'EN',exact:true}).click();await guest.getByRole('button',{name:'Write to us privately'}).click();await guest.getByRole('radio',{name:'Rating 5',exact:true}).check();await guest.getByLabel('Your message (optional)').fill('Lido private browser feedback.');await guest.getByRole('button',{name:'Send feedback',exact:false}).click();await expect(guest.getByRole('heading',{name:'Thank you for writing.'})).toBeVisible();
 await page.locator('.review-filters select').nth(1).selectOption('all');await expect(page.locator('.review-list')).not.toContainText('Lido private browser feedback.');
 await page.getByRole('button',{name:'Card NFC',exact:false}).click();await card.getByRole('button',{name:'Disattiva',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Card in disattivazione'})).toBeVisible();await expect(card).toContainText('Disattivato',{timeout:10000});await guest.goto(url);await expect(guest.getByText('Questo link non è disponibile.',{exact:false})).toBeVisible();await guest.close();
});
