import { expect,test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
test('sala e attesa a 375px: combinazione manuale, fila e accomodamento senza contatti',async({page})=>{
 await page.goto('/r/lido-miseno/staff?view=tables');await page.getByLabel('Password',{exact:true}).fill('bigant2026');await page.getByRole('button',{name:/Accedi al pannello/}).click();
 await page.getByLabel('Filtra per zona').selectOption('Terrazza');await expect(page.locator('.table-card').first()).toBeVisible();
 await page.getByRole('button',{name:'Nuova combinazione',exact:false}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Nome combinazione').fill('Terrazza gruppo browser');await dialog.getByRole('checkbox',{name:/^Tavolo 1 ·/}).check();await dialog.getByRole('checkbox',{name:/^Tavolo 2 ·/}).check();await dialog.getByLabel('Minimo persone').fill('5');await dialog.getByLabel('Massimo persone').fill('8');await dialog.getByRole('button',{name:'Salva modifiche'}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('heading',{name:'Terrazza gruppo browser',exact:true})).toBeVisible();await mkdir('test-results/visual',{recursive:true});await page.locator('.room-groups').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/visual/combinazioni-375.png',fullPage:false});
 await page.getByRole('button',{name:'Prenotazioni',exact:false}).click();await page.locator('.page-heading').getByRole('button',{name:'Nuova prenotazione',exact:false}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Tavolo o combinazione').selectOption({label:'Terrazza gruppo browser · 5–8 · Combinazione manuale'});await dialog.getByRole('button',{name:'6',exact:true}).click();
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const future=new Date(`${today}T12:00Z`);future.setUTCDate(future.getUTCDate()+5);await dialog.locator('#booking-date').fill(future.toISOString().slice(0,10));await dialog.locator('.slot').first().click();await dialog.getByLabel('Nome e cognome').fill('Gruppo telefonata browser');await dialog.getByLabel('Email',{exact:true}).fill('gruppo@example.test');await dialog.getByLabel('Telefono',{exact:true}).fill('3338881122');await dialog.getByRole('button',{name:'Prenota il tavolo'}).click();await expect(dialog).toHaveCount(0);
 await page.locator('#staff-date').fill(future.toISOString().slice(0,10));await expect(page.locator('.reservation-row').filter({hasText:'Gruppo telefonata browser'})).toContainText('Terrazza gruppo browser');await page.getByRole('button',{name:'Oggi',exact:true}).click();
 await page.locator('.waitlist-accordion>summary').click();const queue=page.locator('.waitlist-panel');await queue.getByLabel('Cognome',{exact:true}).fill('Rossi browser');await queue.getByLabel('Persone',{exact:true}).fill('6');await queue.getByRole('button',{name:'Aggiungi in attesa',exact:false}).click();const waiting=queue.locator('.waiting-row').filter({hasText:'Rossi browser'});await expect(waiting).toContainText('C’è una soluzione da valutare');await expect(queue.getByLabel('Email',{exact:true})).toHaveCount(0);await expect(queue.getByLabel('Telefono',{exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('test-results/visual',{recursive:true});await page.screenshot({path:'test-results/visual/attesa-375.png',fullPage:true});
 await waiting.getByRole('button',{name:'Accomoda',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Tavolo o combinazione')).toContainText('Terrazza gruppo browser');await dialog.getByRole('button',{name:'Accomoda',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(waiting).toHaveCount(0);const booking=page.locator('.reservation-row').filter({hasText:'Rossi browser'});await expect(booking).toContainText('Al tavolo');await booking.locator('.guest-button').click();dialog=page.getByRole('dialog');await expect(dialog).toContainText('Tavoli occupati');await expect(dialog).toContainText('Tavolo 1');await expect(dialog).toContainText('Tavolo 2');await dialog.getByRole('button',{name:'Completa',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(booking).toContainText('Completata');
 await queue.getByRole('checkbox',{name:'Mostra anche accomodati e usciti'}).check();await expect(queue.locator('.waiting-row').filter({hasText:'Rossi browser'})).toContainText('Accomodato');await page.getByRole('button',{name:'EN',exact:true}).click();await expect(queue.getByRole('heading',{name:'Welcome those waiting.'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
