'use client';
import { useEffect,useState } from 'react';
import type { CancellationDetails } from '@bigant/types';
import { api,displayTime } from '../lib/api';
import { Brand,LanguageSwitch,ErrorNotice,Loading,Status,useCopy } from './shared';
export function Cancellation({token}:{token:string}) {
 const {t,language}=useCopy();const [data,setData]=useState<CancellationDetails|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;setError('');api<CancellationDetails>(`/public/reservations/${token}`).then(r=>{if(alive)setData(r);}).catch(e=>{if(alive)setError((e as Error).message);});return()=>{alive=false;};},[token,refresh]);
 useEffect(()=>{if(!pending)return;const timer=setTimeout(()=>{setBusy(true);setError('');api(`/public/reservations/${token}/cancel`,{method:'POST'}).then(()=>setRefresh(n=>n+1)).catch(e=>setError((e as Error).message)).finally(()=>{setBusy(false);setPending(false);});},5000);return()=>clearTimeout(timer);},[pending,token]);
 return <div className="public-shell"><header className="public-header"><Brand/><LanguageSwitch/></header><main className="manage-shell"><section className="panel success-card">{!data?(error?<ErrorNotice message={error} onRetry={()=>setRefresh(n=>n+1)}/>:<Loading/>):<><p className="eyebrow accent">{data.tenant.name}</p><h1>{t(data.status==='cancelled'?'cancelledTitle':'manageTitle')}</h1><Status value={data.status}/><div className="receipt-summary"><strong>{new Intl.DateTimeFormat(language,{dateStyle:'full',timeZone:data.tenant.timezone}).format(new Date(data.reserved_at))}</strong><span>{displayTime(data.reserved_at,data.tenant.timezone)} · {data.party_size} {t('peopleUnit')}</span></div>{data.status==='cancelled'?<p className="muted">{t('cancelledHint')}</p>:data.can_cancel?<><p className="muted small">{t('cancelDeadline')} {new Intl.DateTimeFormat(language,{dateStyle:'short',timeStyle:'short',timeZone:data.tenant.timezone}).format(new Date(data.cancellation_deadline))}</p><button className="button secondary wide" onClick={()=>setPending(true)} disabled={busy||pending}>{t(busy?'loading':'cancelBooking')}</button></>:<><p className="muted">{t('cancelTooLate')}</p>{data.tenant.phone&&<a className="button primary" href={`tel:${data.tenant.phone}`}>{t('callVenue')}</a>}</>}{error&&<ErrorNotice message={error}/>}<a href={`/r/${data.tenant.slug}/prenota`} className="text-button">{t('newBooking')}</a></>}</section></main>{pending&&<div className="undo-toast" role="status"><span>{t('cancelScheduled')}</span><button type="button" disabled={busy} onClick={()=>setPending(false)}>{t('undo')}</button></div>}</div>;
}
