'use client';
import { useCallback,useEffect,useRef,useState,type ReactNode } from 'react';
import {consoleLogin,consolePassword,securePassword,consoleStatusInput,type ConsoleIdentity,type ConsoleDetail,type ConsoleAccessResult,type ConsoleStaff} from '@bigant/types';
import {Brand,LanguageSwitch,LanguageProvider,Modal,Loading,ErrorNotice} from './shared';
import {ApiError} from '../lib/api';
import {consoleApi,json,useConsoleCopy,Form,Field,dateLabel} from './console-common';
import {CreateClient,ProfileForm,AccountForm,ServicesForm,AddOperator,EditOperator} from './console-forms';
import {Overview,Clients,TenantSummary,Operators,Audit,useResource} from './console-views';

type Page='overview'|'clients'|'audit';
type Tab='summary'|'profile'|'account'|'services'|'operators'|'audit';
type Dialog={kind:'create'}|{kind:'password'}|{kind:'status';d:ConsoleDetail}|{kind:'add';id:string}|{kind:'edit'|'reset'|'revoke';id:string;s:ConsoleStaff}|{kind:'link';access:ConsoleAccessResult}|null;
export default function Console(){return <LanguageProvider><Admin/></LanguageProvider>;}
function Admin(){
 const {c}=useConsoleCopy();const [identity,setIdentity]=useState<ConsoleIdentity|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [page,setPage]=useState<Page>('overview'),[selected,setSelected]=useState<string|null>(null),[dialog,setDialog]=useState<Dialog>(null),[revision,setRevision]=useState(0);
 const request=useCallback(async<T,>(path:string,options:RequestInit={})=>{try{return await consoleApi<T>(path,options);}catch(e){if(e instanceof ApiError&&e.code==='UNAUTHORIZED'){setIdentity(null);setDialog(null);setSelected(null);}throw e;}},[]);
 const loadIdentity=useCallback(async()=>{setError('');try{setIdentity(await consoleApi('/console/me'));}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:'');}finally{setLoading(false);}},[]);
 useEffect(()=>{void loadIdentity();},[loadIdentity]);
 const refresh=()=>setRevision(v=>v+1);
 const open=(id:string)=>{setSelected(id);setPage('clients');setError('');};
 const navigate=(next:Page)=>{setPage(next);setSelected(null);setError('');};
 const close=()=>setDialog(null);
 async function logout(){try{await request('/console/logout',json('POST',{}));setIdentity(null);setSelected(null);setDialog(null);}catch(e){setError(e instanceof Error?e.message:'');}}
 if(loading)return <Loading/>;
 if(!identity)return <div className="public-shell"><header className="public-header"><Brand/><LanguageSwitch/></header><main className="console-login"><div><span className="eyebrow accent">{c('agency')}</span><h1>{c('intro')}</h1><p>{c('loginHint')}</p><div className="console-login-art" aria-hidden="true"><span>01</span><span>02</span><span>03</span><i>↗</i></div></div><section className="panel console-card"><h2>{c('login')}</h2>{error&&<ErrorNotice message={error} onRetry={()=>void loadIdentity()}/>}<Form schema={consoleLogin} convert={f=>Object.fromEntries(f)} submitLabel={c('login')} onSubmit={async value=>{await consoleApi('/console/login',json('POST',value));setPage('overview');await loadIdentity();}}><label>{c('email')}<input name="email" type="email" required autoComplete="username"/></label><label>{c('password')}<input name="password" type="password" required autoComplete="current-password"/></label></Form></section></main></div>;
 return <div className="console-shell"><aside className="console-sidebar"><Brand href="/admin"/><div className="console-space"><span className="eyebrow">{c('agency')}</span><strong>{c('title')}</strong></div><nav aria-label={c('title')}>{(['overview','clients','audit'] as const).map((p,i)=><button className={page===p?'selected':''} key={p} onClick={()=>navigate(p)} aria-current={page===p?'page':undefined}><span aria-hidden="true">{['◫','▦','≡'][i]}</span>{c(p)}</button>)}</nav><div className="console-sidebar-end"><span>{identity.full_name}</span><small>{identity.email}</small><button className="text-button" onClick={()=>setDialog({kind:'password'})}>{c('security')}</button><button className="text-button" onClick={()=>void logout()}>{c('logout')} ↗</button></div></aside>
 <div className="console-main"><header className="console-topbar"><span>{c('agency')} <span aria-hidden="true">/</span> <strong>{c(page)}</strong></span><LanguageSwitch/></header><main className="console-content">
 {error&&<ErrorNotice message={error}/>}<div className="console-page-heading"><div><span className="eyebrow accent">{c('title')}</span><h1>{selected?c('clients'):c(page)}</h1>{!selected&&<p className="muted">{c(page==='overview'?'overviewHint':page==='clients'?'clientsHint':'auditHint')}</p>}</div><div className="console-actions"><button className="button secondary small-button" onClick={refresh}>{c('refresh')}</button><button className="button primary" onClick={()=>setDialog({kind:'create'})}>+ {c('newClient')}</button></div></div>
 {selected?<Detail key={selected} id={selected} request={request} revision={revision} onSaved={refresh} onBack={()=>navigate('clients')} onDialog={setDialog}/>:page==='overview'?<Overview request={request} revision={revision} onOpen={open}/>:page==='clients'?<Clients request={request} revision={revision} onOpen={open}/>:<Audit request={request} revision={revision}/>}
 </main></div>
 {dialog&&<Modal title={c(dialog.kind==='create'?'newClient':dialog.kind==='password'?'changePassword':dialog.kind==='status'?'statusAction':dialog.kind==='add'?'addOperator':dialog.kind==='edit'?'editOperator':dialog.kind==='reset'?'accessLink':dialog.kind==='revoke'?'revoke':'linkTitle')} onClose={close}>
 {dialog.kind==='create'?<CreateClient request={request} onCreated={result=>{refresh();open(result.id);setDialog({kind:'link',access:result.access});}}/>:
 dialog.kind==='password'?<Form schema={consolePassword.extend({confirm:securePassword}).refine(v=>v.password===v.confirm)} convert={f=>Object.fromEntries(f)} onSubmit={async value=>{await request('/console/password',json('POST',{current_password:value.current_password,password:value.password}));setIdentity(null);close();}}><p className="muted small">{c('passwordHint')}</p><label>{c('currentPassword')}<input name="current_password" type="password" autoComplete="current-password" required/></label><Field name="password" type="password" label={c('newPassword')} required/><Field name="confirm" type="password" label={c('confirmPassword')} required/></Form>:
 dialog.kind==='status'?<StatusDialog d={dialog.d} request={request} onDone={()=>{refresh();close();}} onClose={close}/>:
 dialog.kind==='add'?<AddOperator id={dialog.id} request={request} onCreated={access=>{refresh();setDialog({kind:'link',access});}}/>:
 dialog.kind==='edit'?<EditOperator id={dialog.id} s={dialog.s} request={request} onSaved={()=>{refresh();close();}}/>:
 dialog.kind==='reset'?<ConfirmAction hint={c('newLinkWarning')} onClose={close} onConfirm={async()=>{const access=await request<ConsoleAccessResult>(`/console/tenants/${dialog.id}/staff/${dialog.s.id}/access-link`,json('POST',{}));setDialog({kind:'link',access});refresh();}}><p>{dialog.s.full_name}</p></ConfirmAction>:
 dialog.kind==='revoke'?<ConfirmAction delayed hint={c('revokeHint')} onClose={close} onConfirm={async()=>{await request(`/console/tenants/${dialog.id}/staff/${dialog.s.id}/revoke`,json('POST',{}));refresh();close();}}><p>{dialog.s.full_name}</p></ConfirmAction>:
 dialog.kind==='link'?<AccessLink access={dialog.access}/>:null}
 </Modal>}
 </div>;
}
function Detail({id,request,revision,onSaved,onBack,onDialog}:{id:string;request:typeof consoleApi;revision:number;onSaved:()=>void;onBack:()=>void;onDialog:(value:Dialog)=>void}){
 const {c}=useConsoleCopy();const [tab,setTab]=useState<Tab>('summary');const {data:d,error,loading}=useResource<ConsoleDetail>(request,`/console/tenants/${id}`,undefined,revision);
 return <><button className="text-button" onClick={onBack}>← {c('back')}</button>{loading?<Loading/>:error?<ErrorNotice message={error} onRetry={onSaved}/>:d&&<><div className="console-detail-heading"><div><h2>{d.name}</h2><p className="muted small">/{d.slug} · {c(d.type)} · {c(d.plan)}</p></div><span className={`console-badge ${d.status}`}>{c(d.status)}</span><button className="button secondary small-button" onClick={()=>onDialog({kind:'status',d})}>{c('statusAction')}</button></div><nav className="console-tabs" aria-label={c('clients')}>{(['summary','profile','account','services','operators','audit'] as const).map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)} aria-current={tab===t?'page':undefined}>{c(t)}</button>)}</nav>
 <section key={tab} className="console-tab-content">{tab==='summary'?<TenantSummary d={d}/>:tab==='profile'?<div className="panel console-card"><ProfileForm d={d} request={request} onSaved={onSaved}/></div>:tab==='account'?<div className="panel console-card"><AccountForm d={d} request={request} onSaved={onSaved}/></div>:tab==='services'?<div className="panel console-card"><ServicesForm d={d} request={request} onSaved={onSaved}/></div>:tab==='operators'?<Operators d={d} onAdd={()=>onDialog({kind:'add',id})} onEdit={s=>onDialog({kind:'edit',id,s})} onLink={s=>onDialog({kind:'reset',id,s})} onRevoke={s=>onDialog({kind:'revoke',id,s})}/>:<Audit request={request} tenantId={id} revision={revision}/>}</section></>}</>;
}
function AccessLink({access}:{access:ConsoleAccessResult}){const {c,language}=useConsoleCopy();const [message,setMessage]=useState('');const link=`${window.location.origin}/attiva-accesso#${access.token}`;return <div className="console-form"><p className="muted">{c('linkHint')}</p><label>{c('accessLink')}<input readOnly value={link} onFocus={e=>e.target.select()}/></label><p className="muted small">{c('expires')} {dateLabel(access.expires_at,language)}</p><button className="button primary" onClick={()=>{void navigator.clipboard.writeText(link).then(()=>setMessage(c('copied'))).catch(()=>setMessage(c('copyFailed')));}}>{c('copy')}</button>{message&&<p role="status">{message}</p>}</div>;}
function StatusDialog({d,request,onDone,onClose}:{d:ConsoleDetail;request:typeof consoleApi;onDone:()=>void;onClose:()=>void}){const {c}=useConsoleCopy();const [status,setStatus]=useState(d.status),[reason,setReason]=useState('');return <ConfirmAction delayed hint={c('statusHint')} onClose={onClose} onConfirm={async()=>{const data=consoleStatusInput.parse({status,reason});await request(`/console/tenants/${d.id}/status`,json('PATCH',data));onDone();}}><label>{c('status')}<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{(['active','suspended','cancelled'] as const).map(s=><option value={s} key={s}>{c(s)}</option>)}</select></label><label>{c('reason')}<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} required/><small>{c('reasonHint')}</small></label></ConfirmAction>;}
function ConfirmAction({hint,delayed=false,onConfirm,onClose,children}:{hint:string;delayed?:boolean;onConfirm:()=>Promise<void>;onClose:()=>void;children:ReactNode}){const {c}=useConsoleCopy();const [stage,setStage]=useState<'ready'|'waiting'|'busy'>('ready'),[error,setError]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);async function commit(){setStage('busy');try{await onConfirm();}catch(e){setError(e instanceof Error?e.message:c('invalid'));setStage('ready');}}return <form className="console-form" onSubmit={e=>{e.preventDefault();setError('');if(delayed){setStage('waiting');timer.current=setTimeout(()=>void commit(),5000);}else void commit();}}><p className="muted small">{hint}</p><fieldset disabled={stage!=='ready'}>{children}</fieldset>{error&&<ErrorNotice message={error}/>}<div className="console-actions">{stage==='ready'?<button className="button primary">{c('confirm')}</button>:<span role="status">{c(stage==='waiting'?'delayed':'pending')}</span>}<button className="button secondary" type="button" disabled={stage==='busy'} onClick={onClose}>{c(stage==='waiting'?'undo':'cancel')}</button></div></form>;}
