'use client';
import { useEffect,useState } from 'react';
import type {ConsoleOverview,ConsoleDetail,ConsoleSearchResult,ConsoleAuditRow,ConsoleStaff} from '@bigant/types';
import { useConsoleCopy,consoleApi,money,dateLabel } from './console-common';
import { ErrorNotice,Loading } from './shared';

type Request=typeof consoleApi;
export function useResource<T>(request:Request,path:string,body?:unknown,revision=0){
 const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const encoded=body===undefined?undefined:JSON.stringify(body);
 useEffect(()=>{let cancelled=false;const controller=new AbortController();setLoading(true);setError('');setData(null);request<T>(path,{...(encoded===undefined?{}:{method:'POST',body:encoded}),signal:controller.signal}).then(value=>{if(!cancelled)setData(value);}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;controller.abort();};},[request,path,encoded,revision]);
 return {data,error,loading};
}
export function Metric({label,value,hint,accent=false}:{label:string;value:string|number;hint?:string;accent?:boolean}){return <article className={`console-metric${accent?' console-highlight':''}`}><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</article>;}
export function Overview({request,revision,onOpen}:{request:Request;revision:number;onOpen:(id:string)=>void}){const {c,language}=useConsoleCopy();const {data:d,error,loading}=useResource<ConsoleOverview>(request,'/console/overview',undefined,revision);if(loading)return <Loading/>;if(error)return <ErrorNotice message={error}/>;if(!d)return null;return <>
 <div className="console-metrics"><Metric label={c('activeClients')} value={`${d.active} / ${d.total}`} accent/><Metric label={c('trials')} value={d.trial}/><Metric label={c('mrr')} value={money(d.mrr_cents,language)} hint={c('mrrHint')}/><Metric label={c('attention')} value={d.attention} hint={c('attentionHint')}/></div>
 <div className="console-columns"><section className="panel console-card"><div className="section-heading"><h2>{c('deadlines')}</h2><span className="console-count">{d.due.length}</span></div>{d.due.length?d.due.map((r,i)=><button className="console-row" key={`${r.id}-${i}`} onClick={()=>onOpen(r.id)}><span><strong>{r.name}</strong><small>{c(r.kind==='trial'?'trialEnd':'renewal')}</small></span><span>{dateLabel(r.date,language)} ↗</span></button>):<p className="console-empty">{c('noDeadlines')}</p>}</section>
 <section className="panel console-card"><h2>{c('recent')}</h2>{d.recent.length?d.recent.map(r=><button className="console-row" key={r.id} onClick={()=>onOpen(r.id)}><span><strong>{r.name}</strong><small>/{r.slug}</small></span><span aria-hidden="true">↗</span></button>):<p className="console-empty">{c('empty')}</p>}</section></div>
 <div className="console-footnote"><span className="console-badge">{c(d.mode==='demo'?'demoMode':'liveMode')}</span><span>{c('noSensitive')}</span></div></>;}
export function Clients({request,revision,onOpen}:{request:Request;revision:number;onOpen:(id:string)=>void}){const {c,language}=useConsoleCopy();const [query,setQuery]=useState({q:'',status:'',plan:'',page:1});const {data,error,loading}=useResource<ConsoleSearchResult>(request,'/console/search',{...query,status:query.status||undefined,plan:query.plan||undefined},revision);return <>
 <form className="console-filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setQuery({q:String(f.get('q')),status:String(f.get('status')),plan:String(f.get('plan')),page:1});}}><label className="console-search">{c('search')}<input name="q" type="search" maxLength={120} defaultValue={query.q}/></label><label>{c('status')}<select name="status" defaultValue={query.status}><option value="">{c('allStatuses')}</option>{(['active','suspended','cancelled'] as const).map(s=><option value={s} key={s}>{c(s)}</option>)}</select></label><label>{c('plan')}<select name="plan" defaultValue={query.plan}><option value="">{c('allPlans')}</option>{(['trial','base','pro','full'] as const).map(p=><option value={p} key={p}>{c(p)}</option>)}</select></label><button className="button secondary">{c('searchButton')}</button></form>
 {loading?<Loading/>:error?<ErrorNotice message={error}/>:data&&<><div className="console-client-list">{data.items.length?data.items.map(d=><article className="panel console-client" key={d.id}><div className="console-client-icon" aria-hidden="true">{d.name.slice(0,1).toUpperCase()}</div><div className="console-client-name"><button onClick={()=>onOpen(d.id)}>{d.name}</button><p>{d.account?.contact_name||c('noContact')}</p><small>/{d.slug}</small></div><div className="console-client-plan"><span className={`console-badge ${d.status}`}>{c(d.status)}</span><p>{c(d.plan)} · {money(d.account?.monthly_fee_cents??0,language)}</p></div><button className="button secondary small-button" onClick={()=>onOpen(d.id)} aria-label={`${c('open')} ${d.name}`}>{c('open')} ↗</button></article>):<p className="console-empty">{c('empty')}</p>}</div><Pagination page={data.page} total={data.total} size={data.page_size} onPage={page=>setQuery({...query,page})}/></>}
 </>;}
export function Pagination({page,total,size,onPage}:{page:number;total:number;size:number;onPage:(page:number)=>void}){const {c}=useConsoleCopy();return <div className="console-pagination"><span>{c('page')} {page} {c('of')} {Math.max(1,Math.ceil(total/size))} · {total}</span><button className="button secondary small-button" disabled={page<=1} onClick={()=>onPage(page-1)}>{c('previous')}</button><button className="button secondary small-button" disabled={page*size>=total} onClick={()=>onPage(page+1)}>{c('next')}</button></div>;}
export function TenantSummary({d}:{d:ConsoleDetail}){const {c,label,language}=useConsoleCopy();return <>
 <div className="console-section-title"><h2>{c('usage')}</h2><span>{d.usage.month} · {d.timezone}</span></div><div className="console-metrics"><Metric label={c('bookings')} value={d.usage.reservations}/><Metric label={c('covers')} value={d.usage.covers}/><Metric label={c('cancellations')} value={d.usage.cancelled}/><Metric label={c('noShows')} value={d.usage.no_shows}/></div>
 <div className="console-columns"><section className="panel console-card"><h2>{c('setup')}</h2><p className="muted small">{c('setupHint')}</p><ul className="console-checklist">{d.checks.map(x=><li key={x.key}><span className={x.complete?'console-check-ok':'console-check-missing'} aria-hidden="true">{x.complete?'✓':'○'}</span><span>{c(`check_${x.key}`)}</span><small>{c(x.complete?'complete':'missing')}</small></li>)}</ul></section>
 <section className="panel console-card"><h2>{c('contact')}</h2><p>{d.account?.contact_name||c('noContact')}</p>{d.account?.contact_email&&<p><a href={`mailto:${d.account.contact_email}`}>{d.account.contact_email}</a></p>}<dl className="console-dl"><div><dt>{c('plan')}</dt><dd>{c(d.plan)}</dd></div><div><dt>{c('monthlyFee')}</dt><dd>{money(d.account?.monthly_fee_cents??0,language)}</dd></div><div><dt>{c('trialEnd')}</dt><dd>{dateLabel(d.account?.trial_ends_at??null,language)}</dd></div><div><dt>{c('renewal')}</dt><dd>{dateLabel(d.account?.renewal_at??null,language)}</dd></div></dl><div className="console-actions"><a className="button secondary small-button" href={`/r/${d.slug}`} target="_blank" rel="noreferrer">{c('publicPage')} ↗</a><a className="button secondary small-button" href={`/r/${d.slug}/staff`} target="_blank" rel="noreferrer">{c('staffPage')} ↗</a></div><p className="small muted">{c('staffHint')}</p></section></div>
 <section className="panel console-card"><div className="section-heading"><h2>{c('notifications')}</h2><span>{c('smsUsed')}: {d.usage.sms_used} / {d.settings.sms_monthly_cap}</span></div><p className="small muted">{c('notificationStatus')}</p>{d.usage.notifications.length?<div className="console-deliveries">{d.usage.notifications.map(n=><div key={`${n.channel}-${n.status}`}><span>{label(n.channel)} · {label(n.status)}</span><strong>{n.count}</strong></div>)}</div>:<p className="console-empty">{c('empty')}</p>}</section>
 <p className="console-footnote">{c('allTime')}: {d.counts.tables} {c('tables').toLowerCase()} · {d.counts.customers} {c('customers').toLowerCase()} · {d.counts.bookings} {c('bookings').toLowerCase()}. {c('noSensitive')}</p>
 </>;}
export function Operators({d,onAdd,onEdit,onLink,onRevoke}:{d:ConsoleDetail;onAdd:()=>void;onEdit:(s:ConsoleStaff)=>void;onLink:(s:ConsoleStaff)=>void;onRevoke:(s:ConsoleStaff)=>void}){const {c,language}=useConsoleCopy();return <><div className="section-heading"><h2>{c('operators')}</h2><button className="button primary" disabled={d.status!=='active'} onClick={onAdd}>+ {c('addOperator')}</button></div><div className="console-operators">{d.staff.map(s=><article className="panel console-card" key={s.id}><div className="section-heading"><div><h3>{s.full_name}</h3><p className="muted small">{s.email}</p></div><span className={`console-badge ${s.status}`}>{c(s.status)}</span></div><p className="small">{c(s.role)} · {c('lastLogin')}: {s.last_login_at?dateLabel(s.last_login_at,language):c('never')}</p><div className="console-actions"><button className="button secondary small-button" onClick={()=>onEdit(s)}>{c('editOperator')}</button><button className="text-button" disabled={s.status!=='active'||d.status!=='active'} onClick={()=>onLink(s)}>{c('accessLink')}</button><button className="text-button danger" onClick={()=>onRevoke(s)}>{c('revoke')}</button></div></article>)}</div></>;}
export function Audit({request,tenantId,revision}:{request:Request;tenantId?:string;revision:number}){const {c,label,language}=useConsoleCopy();const [page,setPage]=useState(1);const {data,error,loading}=useResource<{items:ConsoleAuditRow[];total:number;page:number}>(request,'/console/audit',{tenant_id:tenantId,page},revision);return <><p className="muted small">{c('auditHint')}</p>{loading?<Loading/>:error?<ErrorNotice message={error}/>:data&&<><div className="console-audit">{data.items.length?data.items.map(r=><article key={r.id}><span className="console-audit-dot" aria-hidden="true"/><div><strong>{label(r.action)}</strong><p>{r.tenant_name??c('platform')} · {r.actor}</p>{typeof r.metadata.reason==='string'&&<p className="console-audit-reason">{r.metadata.reason}</p>}{typeof r.metadata.plan==='string'&&<small>{c('plan')}: {label(r.metadata.plan)}{typeof r.metadata.monthly_fee_cents==='number'?` · ${money(r.metadata.monthly_fee_cents,language)}`:''}</small>}{typeof r.metadata.to==='string'&&<small>{label(String(r.metadata.from))} → {label(r.metadata.to)}</small>}</div><time dateTime={r.created_at}>{dateLabel(r.created_at,language)}</time></article>):<p className="console-empty">{c('empty')}</p>}</div><Pagination page={page} total={data.total} size={50} onPage={setPage}/></>}</>;}
