'use client';
import {consoleCreateInput,consoleProfileInput,consoleAccountInput,consoleServicesInput,consoleStaffInput,consoleStaffPatch,type ConsoleDetail,type ConsoleAccessResult,type ConsoleStaff,type ConsoleCreateInput} from '@bigant/types';
import { Field,Select,Toggle,Form,optional,feeCents,useConsoleCopy,json } from './console-common';

type Request=<T>(path:string,options?:RequestInit)=>Promise<T>;
const plans=['trial','base','pro','full'] as const;
const types=['restaurant','bar','hotel','beach_club'] as const;
const profile=(f:FormData)=>({name:f.get('name'),type:f.get('type'),address:optional(f.get('address')),phone:optional(f.get('phone')),google_place_id:optional(f.get('google_place_id')),locale_default:f.get('locale_default')});
function ProfileFields({d}:{d?:ConsoleDetail}){const {c}=useConsoleCopy();return <div className="form-grid"><Field name="name" label={c('name')} value={d?.name} required/><Select name="type" label={c('type')} value={d?.type??'restaurant'} values={types}/><Field name="address" label={c('address')} value={d?.address}/><Field name="phone" label={c('phone')} value={d?.phone} type="tel"/><Field name="google_place_id" label={c('google')} value={d?.google_place_id}/><Select name="locale_default" label={c('locale')} value={d?.locale_default??'it'} values={['it','en']}/></div>;}
export function CreateClient({request,onCreated}:{request:Request;onCreated:(value:{id:string;access:ConsoleAccessResult})=>void}){const {c}=useConsoleCopy();return <Form schema={consoleCreateInput} convert={f=>({...profile(f),slug:f.get('slug'),owner_name:f.get('owner_name'),owner_email:f.get('owner_email'),plan:f.get('plan')})} onSubmit={async(data:ConsoleCreateInput)=>onCreated(await request('/console/tenants',json('POST',data)))} submitLabel={c('create')}><p className="muted small">{c('createHint')}</p><ProfileFields/><div className="form-grid"><Field name="slug" label={c('slug')} hint={c('slugHint')} required/><Select name="plan" label={c('plan')} value="trial" values={plans}/><Field name="owner_name" label={c('ownerName')} required/><Field name="owner_email" label={c('ownerEmail')} type="email" required/></div></Form>;}
export function ProfileForm({d,request,onSaved}:{d:ConsoleDetail;request:Request;onSaved:()=>void}){return <Form schema={consoleProfileInput} convert={profile} success onSubmit={async value=>{await request(`/console/tenants/${d.id}/profile`,json('PATCH',value));onSaved();}}><ProfileFields d={d}/></Form>;}
export function AccountForm({d,request,onSaved}:{d:ConsoleDetail;request:Request;onSaved:()=>void}){const {c}=useConsoleCopy();const a=d.account;return <Form schema={consoleAccountInput} convert={f=>({plan:f.get('plan'),contact_name:f.get('contact_name'),contact_email:optional(f.get('contact_email')),monthly_fee_cents:feeCents(f.get('fee')),trial_ends_at:optional(f.get('trial_ends_at')),renewal_at:optional(f.get('renewal_at')),notes:f.get('notes')})} success onSubmit={async value=>{await request(`/console/tenants/${d.id}/account`,json('PATCH',value));onSaved();}}><p className="muted small">{c('billingHint')}</p><div className="form-grid"><Select name="plan" label={c('plan')} value={d.plan} values={plans}/><Field name="fee" label={c('monthlyFee')} value={`${Math.floor((a?.monthly_fee_cents??0)/100)}.${String((a?.monthly_fee_cents??0)%100).padStart(2,'0')}`} required/><Field name="contact_name" label={c('contactName')} value={a?.contact_name}/><Field name="contact_email" label={c('contactEmail')} type="email" value={a?.contact_email}/><Field name="trial_ends_at" label={c('trialEnd')} type="date" value={a?.trial_ends_at}/><Field name="renewal_at" label={c('renewal')} type="date" value={a?.renewal_at}/><label className="span-two">{c('notes')}<textarea name="notes" rows={5} maxLength={5000} defaultValue={a?.notes??''}/></label></div></Form>;}
const bookingNumbers=['total_capacity','max_covers_per_slot','slot_granularity_min','turn_duration_min','min_lead_time_min','max_advance_days','cancellation_deadline_hours'] as const;
const notificationNumbers=['sms_monthly_cap','reminder_hours_before','retention_months'] as const;
export function ServicesForm({d,request,onSaved}:{d:ConsoleDetail;request:Request;onSaved:()=>void}){const {c}=useConsoleCopy();const s=d.settings;return <Form schema={consoleServicesInput} convert={f=>({booking:{...Object.fromEntries(bookingNumbers.map(k=>[k,Number(f.get(k))])),auto_confirm:f.has('auto_confirm'),auto_assign_tables:f.has('auto_assign_tables')},notifications:{...Object.fromEntries(notificationNumbers.map(k=>[k,Number(f.get(k))])),sms_enabled:f.has('sms_enabled'),privacy_contact_email:optional(f.get('privacy_contact_email'))}})} success onSubmit={async value=>{await request(`/console/tenants/${d.id}/services`,json('PATCH',value));onSaved();}}><p className="muted small">{c('bookingHint')}</p><div className="console-toggles"><Toggle name="auto_confirm" label={c('autoConfirm')} value={s.auto_confirm}/><Toggle name="auto_assign_tables" label={c('autoAssign')} value={s.auto_assign_tables}/></div><div className="form-grid">{bookingNumbers.map(k=><Field key={k} name={k} label={c(k)} value={s[k]} type="number" required min={0}/>)}</div><h3>{c('notifications')}</h3><p className="muted small">{c('smsHint')}</p><Toggle name="sms_enabled" label={c('sms_enabled')} value={s.sms_enabled} disabled={!['pro','full'].includes(d.plan)}/><div className="form-grid">{notificationNumbers.map(k=><Field key={k} name={k} label={c(k)} value={s[k]} type="number" required min={0}/>)}<Field name="privacy_contact_email" label={c('privacy_contact_email')} type="email" value={s.privacy_contact_email}/></div></Form>;}
export function AddOperator({id,request,onCreated}:{id:string;request:Request;onCreated:(value:ConsoleAccessResult)=>void}){const {c}=useConsoleCopy();return <Form schema={consoleStaffInput} convert={f=>Object.fromEntries(f)} onSubmit={async value=>onCreated(await request(`/console/tenants/${id}/staff`,json('POST',value)))} submitLabel={c('addOperator')}><div className="form-grid"><Field name="full_name" label={c('operatorName')} required/><Field name="email" label={c('email')} type="email" required/><Select name="role" label={c('role')} value="staff" values={['owner','staff']}/></div></Form>;}
export function EditOperator({id,s,request,onSaved}:{id:string;s:ConsoleStaff;request:Request;onSaved:()=>void}){const {c}=useConsoleCopy();return <Form schema={consoleStaffPatch} convert={f=>Object.fromEntries(f)} onSubmit={async value=>{await request(`/console/tenants/${id}/staff/${s.id}`,json('PATCH',value));onSaved();}}><p>{s.full_name}</p><div className="form-grid"><Select name="role" label={c('role')} value={s.role} values={['owner','staff']}/><Select name="status" label={c('status')} value={s.status} values={['active','disabled']}/></div></Form>;}
