'use client';
import { useEffect,useState } from 'react';
import type { CustomerRecord,StaffProfile } from '@bigant/types';
import { staffApi } from '../lib/api';
import { useCopy,Loading,ErrorNotice,Modal } from './shared';
export function CustomersPanel({profile,schedule}:{profile:StaffProfile;schedule:(label:string,work:()=>Promise<unknown>)=>void}) {
 const {t}=useCopy();const [rows,setRows]=useState<CustomerRecord[]>([]),[q,setQ]=useState(''),[query,setQuery]=useState(''),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<CustomerRecord|null>(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);staffApi<{items:CustomerRecord[];next_cursor:string|null}>('/customers/search',{method:'POST',body:JSON.stringify({q:query})}).then(r=>{if(alive){setRows(r.items);setCursor(r.next_cursor);setError('');}}).catch(e=>{if(alive)setError((e as Error).message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[query,revision]);
 async function save(revoke=false){if(!selected)return;setBusy(true);try{await staffApi(`/customers/${selected.id}`,{method:'PATCH',body:JSON.stringify(revoke?{marketing_consent:false}:{notes})});setSelected(null);setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(){setBusy(true);setError('');try{const blob=await staffApi<Blob>('/customers/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='bigant-clienti.csv';link.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="content-area"><div className="page-heading"><div><p className="eyebrow accent">{t('customers')}</p><h1>{t('customersTitle')}</h1><p className="muted">{t('customersHint')}</p></div>{profile.role==='owner'&&<button className="button secondary" disabled={busy} onClick={()=>{void download();}}>{t('exportCustomers')} ↓</button>}</div><form className="toolbar" onSubmit={e=>{e.preventDefault();setQuery(q);}}><label>{t('customerSearch')}<input type="search" value={q} maxLength={120} onChange={e=>setQ(e.target.value)}/></label><button className="button secondary">{t('customerSearch')}</button></form>{error&&<ErrorNotice message={error} onRetry={()=>setRevision(r=>r+1)}/>}<section className="panel">{loading?<Loading/>:!rows.length?<p className="empty-state">{t('noCustomers')}</p>:rows.map(row=><article className="delivery-row" key={row.id}><div><strong>{row.anonymized_at?t('anonymizedCustomer'):row.full_name}</strong><small>{row.phone_e164} {row.email}</small></div><button className="button secondary compact" onClick={()=>{setSelected(row);setNotes(row.notes);}}>{t('customerDetails')}</button></article>)}</section>{cursor&&<button className="button secondary" disabled={loading} onClick={async()=>{setLoading(true);try{const r=await staffApi<{items:CustomerRecord[];next_cursor:string|null}>('/customers/search',{method:'POST',body:JSON.stringify({q:query,cursor})});setRows(old=>[...old,...r.items]);setCursor(r.next_cursor);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}}>{t('loadMore')}</button>}{selected&&<Modal title={selected.anonymized_at?t('anonymizedCustomer'):selected.full_name} onClose={()=>setSelected(null)}>{selected.anonymized_at?<p>{t('anonymizedHint')}</p>:<><p>{selected.phone_e164}<br/>{selected.email}</p><label>{t('customerNotes')}<textarea value={notes} maxLength={2000} rows={4} onChange={e=>setNotes(e.target.value)}/></label><button className="button primary" disabled={busy} onClick={()=>{void save();}}>{t('save')}</button>{selected.marketing_consent&&<button className="button secondary" disabled={busy} onClick={()=>{void save(true);}}>{t('marketingConsent')} · {t('remove')}</button>}{profile.role==='owner'&&<button className="button danger" disabled={busy} onClick={()=>{const id=selected.id;schedule(t('anonymizeScheduled'),async()=>{await staffApi(`/customers/${id}`,{method:'DELETE'});setRevision(r=>r+1);});setSelected(null);}}>{t('anonymizeCustomer')}</button>}</>}</Modal>}</section>;
}
