'use client';
import { useEffect,useState } from 'react';
import type { CustomerRecord,StaffProfile,CustomerReservationHistory } from '@bigant/types';
import { staffApi } from '../lib/api';
import { useCopy,Loading,ErrorNotice,Modal,Status } from './shared';
type CustomerPage={items:CustomerRecord[];next_cursor:string|null};
export function CustomersPanel({profile,schedule,pending=false}:{profile:StaffProfile;schedule:(label:string,work:()=>Promise<unknown>)=>void;pending?:boolean}) {
 const {t,language}=useCopy();
 const [rows,setRows]=useState<CustomerRecord[]>([]),[q,setQ]=useState(''),[query,setQuery]=useState(''),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<CustomerRecord|null>(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[success,setSuccess]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setCursor(null);setError('');staffApi<CustomerPage>('/customers/search',{method:'POST',body:JSON.stringify({q:query})}).then(r=>{if(alive){setRows(r.items);setCursor(r.next_cursor);}}).catch(e=>{if(alive)setError((e as Error).message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[query,revision]);
 const date=(value:string)=>new Intl.DateTimeFormat(language==='it'?'it-IT':'en-GB',{timeZone:profile.tenant.timezone,dateStyle:'medium'}).format(new Date(value));
 async function save(revoke=false){if(!selected)return;setBusy(true);setError('');setSuccess('');try{await staffApi(`/customers/${selected.id}`,{method:'PATCH',body:JSON.stringify(revoke?{marketing_consent:false}:{notes})});setSelected(null);setSuccess(t('saved'));setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(){setBusy(true);setError('');setSuccess('');try{const blob=await staffApi<Blob>('/customers/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='bigant-clienti.csv';link.click();URL.revokeObjectURL(url);setSuccess(t('exportedCustomers'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function more(){if(!cursor)return;setLoadingMore(true);setError('');try{const r=await staffApi<CustomerPage>('/customers/search',{method:'POST',body:JSON.stringify({q:query,cursor})});setRows(old=>[...old,...r.items.filter(row=>!old.some(previous=>previous.id===row.id))]);setCursor(r.next_cursor);}catch(e){setError((e as Error).message);}finally{setLoadingMore(false);}}
 return <section className="content-area">
  <div className="page-heading"><div><p className="eyebrow accent">{t('customers')}</p><h1>{t('customersTitle')}</h1><p className="muted">{t('customersHint')}</p></div>{profile.role==='owner'&&<button className="button secondary" disabled={busy} onClick={()=>{void download();}}>{t('exportCustomers')} ↓</button>}</div>
  <form className="toolbar" onSubmit={e=>{e.preventDefault();setQuery(q.trim());}}><label>{t('customerSearch')}<input type="search" value={q} maxLength={120} placeholder={t('customerSearchHint')} disabled={loadingMore} onChange={e=>setQ(e.target.value)}/></label><button className="button secondary" disabled={loading||loadingMore}>{t('customerSearch')}</button>{(query||q)&&<button type="button" className="text-button" disabled={loadingMore} onClick={()=>{setQ('');setQuery('');}}>{t('customerClearSearch')}</button>}</form>
  {error&&!selected&&<ErrorNotice message={error} onRetry={()=>setRevision(r=>r+1)}/>}{success&&<p className="notice success" role="status">{success}</p>}
  <section className="panel">{loading?<Loading/>:error&&!rows.length?null:!rows.length?<p className="empty-state">{t(query?'customerNoMatches':'noCustomers')}</p>:rows.map(row=><article className="delivery-row" key={row.id}><div><strong>{row.anonymized_at?t('anonymizedCustomer'):row.full_name}</strong><small>{row.phone_e164} {row.email}</small><small className="customer-meta">{row.total_visits} {t('customerVisits').toLocaleLowerCase()}{row.no_show_count>0&&` · ${row.no_show_count} ${t('customerNoShows').toLocaleLowerCase()}`}</small></div><button className="button secondary compact" aria-label={`${t('customerDetails')}: ${row.anonymized_at?t('anonymizedCustomer'):row.full_name}`} onClick={()=>{setSelected(row);setNotes(row.notes);setError('');setSuccess('');}}>{t('customerDetails')}</button></article>)}</section>
  {cursor&&<button className="button secondary" disabled={loadingMore} onClick={()=>void more()}>{t(loadingMore?'loading':'loadMore')}</button>}
  {selected&&<Modal title={selected.anonymized_at?t('anonymizedCustomer'):selected.full_name} onClose={()=>setSelected(null)}>
   <div className="customer-history"><p><strong>{t('customerVisits')}:</strong> {selected.total_visits} · <strong>{t('customerNoShows')}:</strong> {selected.no_show_count}</p><p className="muted small">{t('customerLastVisit')}: {selected.last_visit_at?date(selected.last_visit_at):t('customerNoVisit')}</p></div>
   <CustomerHistory key={selected.id} customerId={selected.id} zone={profile.tenant.timezone}/>
   {selected.anonymized_at?<p className="notice">{t('anonymizedHint')}</p>:<>
    <p>{selected.phone_e164&&<a href={`tel:${selected.phone_e164}`}>{selected.phone_e164}</a>}<br/>{selected.email&&<a href={`mailto:${selected.email}`}>{selected.email}</a>}</p>
    <form className="editor-form" onSubmit={e=>{e.preventDefault();void save();}}><label>{t('customerNotes')}<textarea value={notes} maxLength={2000} rows={4} onChange={e=>setNotes(e.target.value)}/></label>{error&&<ErrorNotice message={error}/>}<button className="button primary" disabled={busy||pending}>{t(busy?'saving':'save')}</button></form>
    <div className="detail-actions"><p className="small muted">{t('marketingConsent')}: {t(selected.marketing_consent?'customerConsentYes':'customerConsentNo')}{selected.marketing_consent&&selected.marketing_consent_at&&` · ${date(selected.marketing_consent_at)}`}</p>{selected.marketing_consent&&<button className="button secondary" disabled={busy||pending} onClick={()=>{void save(true);}}>{t('customerRevokeConsent')}</button>}</div>
    {profile.role==='owner'&&<div className="detail-actions"><p className="small muted">{t('customerAnonymizeHint')}</p><button className="button secondary danger" disabled={busy||pending} onClick={()=>{const id=selected.id;schedule(t('anonymizeScheduled'),async()=>{await staffApi(`/customers/${id}`,{method:'DELETE'});setRevision(r=>r+1);});setSelected(null);}}>{t('anonymizeCustomer')}</button></div>}
   </>}
  </Modal>}
 </section>;
}

function CustomerHistory({customerId,zone}:{customerId:string;zone:string}){
 const {t,language}=useCopy();const [history,setHistory]=useState<CustomerReservationHistory|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;setError('');staffApi<CustomerReservationHistory>(`/customers/${customerId}/reservations`).then(result=>{if(alive)setHistory(result);}).catch(reason=>{if(alive)setError((reason as Error).message);});return()=>{alive=false;};},[customerId,revision]);
 return <section className="customer-history-list"><h3>{t('customerHistoryTitle')}</h3>{error?<ErrorNotice message={error} onRetry={()=>setRevision(value=>value+1)}/>:!history?<Loading/>:!history.items.length?<p className="small muted">{t('customerHistoryEmpty')}</p>:<>{history.has_more&&<p className="small muted">{t('customerHistoryLimit')}</p>}{history.items.map(row=><article className="delivery-row" key={row.id}><div><strong>{new Intl.DateTimeFormat(language==='it'?'it-IT':'en-GB',{timeZone:zone,dateStyle:'medium',timeStyle:'short'}).format(new Date(row.reserved_at))}</strong><small>{row.party_size} {t('peopleUnit')} · {t(`source_${row.source}`)}</small></div><Status value={row.status}/></article>)}</>}</section>;
}
