'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { type StaffProfile,type NotificationSettings,type NotificationOverview,type DeliveryRecord,notificationSettingsInput } from '@bigant/types';
import { type UiKey } from '@bigant/i18n';
import { staffApi } from '../lib/api';
import { useCopy,Loading,ErrorNotice } from './shared';
import { PwaTools } from './pwa';
export function NotificationsPanel({profile}:{profile:StaffProfile}) {
 const {t,language}=useCopy();const [settings,setSettings]=useState<NotificationSettings|null>(null),[summary,setSummary]=useState<NotificationOverview|null>(null),[rows,setRows]=useState<DeliveryRecord[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;Promise.all([staffApi<NotificationSettings>('/notifications/settings'),staffApi<NotificationOverview>('/notifications/summary'),staffApi<DeliveryRecord[]>('/notifications')]).then(([s,v,r])=>{if(alive){setSettings(s);setSummary(v);setRows(r);setError('');}}).catch(e=>{if(alive)setError((e as Error).message);});return()=>{alive=false;};},[revision]);
 useEffect(()=>{let alive=true;const refresh=()=>{if(document.hidden)return;Promise.all([staffApi<NotificationOverview>('/notifications/summary'),staffApi<DeliveryRecord[]>('/notifications')]).then(([v,r])=>{if(alive){setSummary(v);setRows(r);}}).catch(e=>{if(alive)setError((e as Error).message);});};const timer=setInterval(refresh,30000);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[]);
 async function save(event:FormEvent){event.preventDefault();const parsed=notificationSettingsInput.safeParse(settings);if(!parsed.success){setError(t('invalidForm'));return;}setBusy(true);setSaved(false);try{await staffApi('/notifications/settings',{method:'PATCH',body:JSON.stringify(parsed.data)});setSaved(true);setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!settings||!summary)return error?<ErrorNotice message={error} onRetry={()=>setRevision(r=>r+1)}/>:<Loading/>;
 return <section className="content-area"><div className="page-heading"><div><p className="eyebrow accent">{t('notifications')}</p><h1>{t('notificationTitle')}</h1><p className="muted">{t('notificationHint')}</p></div></div><p className="notice subtle">{t(summary.mode==='demo'?'demoDelivery':'liveDelivery')}</p><div className="stats-grid review-stats">{[['queuedMessages',summary.queued],['simulatedMessages',summary.simulated],['acceptedMessages',summary.accepted],['uncertainMessages',summary.uncertain]] .map(([label,count])=><div className="stat-card" key={label}><small>{t(label as UiKey)}</small><strong>{count}</strong></div>)}</div><section className="panel settings-section"><h2>{t('smsUsage')}: {summary.sms_used} / {summary.sms_cap}</h2><p>{t('smsFallback')}: {summary.sms_fallbacks}</p><p className="muted small">{t('smsCapHint')}</p></section>{error&&<ErrorNotice message={error} onRetry={()=>setRevision(r=>r+1)}/>}<form onSubmit={save} className="panel settings-section"><h2>{t('settings')}</h2><fieldset disabled={profile.role!=='owner'||busy}><div className="form-grid"><label>{t('reminderHours')}<input type="number" min={1} max={72} value={settings.reminder_hours_before} onChange={e=>setSettings({...settings,reminder_hours_before:Number(e.target.value)})}/></label><label>{t('smsCap')}<input type="number" min={0} max={10000} value={settings.sms_monthly_cap} onChange={e=>setSettings({...settings,sms_monthly_cap:Number(e.target.value)})}/></label><label>{t('retentionMonths')}<input type="number" min={1} max={120} value={settings.retention_months} onChange={e=>setSettings({...settings,retention_months:Number(e.target.value)})}/></label><label>{t('privacyContact')}<input type="email" value={settings.privacy_contact_email??''} onChange={e=>setSettings({...settings,privacy_contact_email:e.target.value||null})}/></label></div><label className="check-label"><input type="checkbox" checked={settings.sms_enabled} onChange={e=>setSettings({...settings,sms_enabled:e.target.checked})}/>{t('smsEnabled')}</label>{profile.role==='owner'&&<button className="button primary" disabled={busy}>{t(busy?'saving':'save')}</button>}</fieldset>{saved&&<p role="status">{t('saved')}</p>}{profile.role!=='owner'&&<p className="muted">{t('ownerOnly')}</p>}</form><PwaTools slug={profile.tenant.slug}/><section className="panel settings-section"><h2>{t('deliveryHistory')}</h2>{!rows.length?<p className="muted">{t('noDeliveries')}</p>:rows.map(row=><article key={row.id} className="delivery-row"><div><strong>{t((['created','pending','confirmed','reminder','cancellation','staff_cancellation','private_review','new_reservation'].includes(row.event_name)?`event_${row.event_name}`:'event_legacy') as UiKey)}</strong><small>{new Intl.DateTimeFormat(language,{timeZone:profile.tenant.timezone,dateStyle:'short',timeStyle:'short'}).format(new Date(row.created_at))} · {row.channel.toUpperCase()}</small></div><span>{t(`delivery_${row.status}`)}</span></article>)}</section></section>;
}
