'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { groupInput,type TableRecord,type GroupRecord } from '@bigant/types';
import { staffApi } from '../lib/api';
import { useCopy,Loading,ErrorNotice,Modal } from './shared';
export function RoomGroups({tables,owner}:{tables:TableRecord[];owner:boolean}){
 const {t}=useCopy();const [groups,setGroups]=useState<GroupRecord[]|null>(null),[revision,setRevision]=useState(0),[adding,setAdding]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;staffApi<GroupRecord[]>('/table-groups').then(r=>{if(alive)setGroups(r);}).catch(e=>{if(alive)setError((e as Error).message);});return()=>{alive=false;};},[revision,tables]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const parsed=groupInput.safeParse({name:f.get('name'),min_capacity:Number(f.get('min_capacity')),max_capacity:Number(f.get('max_capacity')),table_ids:f.getAll('table_ids')});if(!parsed.success){setError(t('invalidForm'));return;}setBusy(true);setError('');try{await staffApi('/table-groups',{method:'POST',body:JSON.stringify(parsed.data)});setAdding(false);setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function toggle(group:GroupRecord){setBusy(true);setError('');try{await staffApi(`/table-groups/${group.id}`,{method:'PATCH',body:JSON.stringify({active:!group.active})});setRevision(r=>r+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="room-groups"><div className="section-heading"><h2>{t('tableGroups')}</h2>{owner&&<button className="button secondary" onClick={()=>{setAdding(true);setError('');}} disabled={busy}>+ {t('newGroup')}</button>}</div><p className="muted room-hint">{t('groupsHint')}</p>{error&&!adding&&<ErrorNotice message={error} onRetry={()=>setRevision(r=>r+1)}/>}{!groups?<Loading/>:!groups.length?<p className="notice">{t('noGroups')}</p>:<div className="tables-grid">{groups.map(group=>{const blocked=group.members.some(m=>!m.table.active)||group.max_capacity>group.members.reduce((sum,m)=>sum+m.table.max_capacity,0);return <article className={`panel table-card ${!group.active?'inactive':''}`} key={group.id}><div className="section-heading"><h3>{group.name}</h3><span className={`table-state ${group.active?'on':''}`}>{t(group.active?'active':'inactive')}</span></div><p>{group.members.map(m=>m.table.name).join(' + ')}</p><p className="muted">{group.min_capacity}–{group.max_capacity} {t('peopleUnit')}</p>{blocked&&<p className="notice">{t('groupBlocked')}</p>}{owner&&<button className="button secondary wide" disabled={busy||(!group.active&&blocked)} onClick={()=>void toggle(group)}>{t(group.active?'groupDeactivate':'groupActivate')}</button>}</article>;})}</div>}{adding&&<Modal title={t('newGroup')} onClose={()=>setAdding(false)}><form className="editor-form" onSubmit={save}><p className="muted">{t('groupFixed')}</p><label>{t('groupName')}<input name="name" required maxLength={80}/></label><fieldset className="group-checks"><legend>{t('groupTables')}</legend>{tables.filter(tb=>tb.active).map(tb=><label className="check-label" key={tb.id}><input type="checkbox" name="table_ids" value={tb.id}/>{tb.name} · {tb.zone??t('noZone')} · {tb.max_capacity} {t('peopleUnit')}</label>)}</fieldset><div className="form-grid"><label>{t('minCapacity')}<input name="min_capacity" type="number" min="1" max="500" required defaultValue={1}/></label><label>{t('maxCapacity')}<input name="max_capacity" type="number" min="1" max="500" required defaultValue={8}/></label></div>{error&&<ErrorNotice message={error}/>}<button className="button primary wide" disabled={busy}>{t(busy?'saving':'save')}</button></form></Modal>}</section>;
}
