export const notificationMessages={
 it:{customerDetails:'Dettagli ospite',
  notifications:'Notifiche',customers:'Clienti',notificationTitle:'Tieni tutti aggiornati.',notificationHint:'Consegne e consumi del tuo locale. Gli esiti incerti richiedono verifica, senza reinvii automatici.',
  demoDelivery:'Prova locale: i messaggi sono simulati. Nessuna email, SMS o push viene spedita.',liveDelivery:'Il servizio è configurato per gli invii reali. Accettato dal fornitore non significa consegnato.',
  queuedMessages:'In coda',simulatedMessages:'Simulati',acceptedMessages:'Accettati dal fornitore',uncertainMessages:'Da verificare',failedMessages:'Non inviati',smsUsage:'SMS nel mese',smsFallback:'Passaggi a email',smsCapHint:'Il tetto conta i messaggi; il costo può dipendere dai segmenti. Gli invii incerti consumano il tetto prudenzialmente.',
  smsEnabled:'Abilita SMS (piano Pro/Full)',smsCap:'Tetto mensile SMS',reminderHours:'Promemoria (ore prima)',retentionMonths:'Conservazione clienti (mesi)',privacyContact:'Email privacy e risposte del locale',deliveryHistory:'Ultime consegne',noDeliveries:'Le prossime prenotazioni creeranno qui le prime consegne.',
  delivery_queued:'In coda',delivery_processing:'In lavorazione',delivery_sent:'Accettato',delivery_failed:'Non inviato',delivery_uncertain:'Esito da verificare',delivery_simulated:'Simulato',delivery_skipped:'Non necessario',
  event_created:'Conferma prenotazione',event_pending:'Attesa conferma',event_confirmed:'Conferma del locale',event_reminder:'Promemoria',event_cancellation:'Disdetta',event_staff_cancellation:'Disdetta del locale',event_private_review:'Feedback privato',event_new_reservation:'Nuova prenotazione',event_legacy:'Storico',
  installTitle:'Il tuo locale, sempre a portata di mano.',installHint:'Su iPhone: Condividi → Aggiungi alla schermata Home. Su Android usa Installa nel browser.',installApp:'Installa BigAnt',enablePush:'Attiva notifiche sul dispositivo',disablePush:'Disattiva notifiche su questo dispositivo',pushReady:'Dispositivo abilitato',pushUnavailable:'Le push reali richiedono HTTPS, chiavi e servizio configurati. Il pannello continua a funzionare.',pushDenied:'Le notifiche sono bloccate nelle impostazioni del browser. Puoi continuare dal pannello.',
  customersTitle:'I tuoi ospiti.',customersHint:'Contatti riservati al locale. L’export esclude allergie e note libere.',customerSearch:'Cerca un ospite',exportCustomers:'Esporta CSV',exportedCustomers:'CSV scaricato',noCustomers:'Gli ospiti compariranno dopo la prima prenotazione.',customerNotes:'Note interne ospite',marketingConsent:'Consenso marketing',anonymizeCustomer:'Anonimizza ospite',anonymizeScheduled:'Anonimizzazione tra 5 secondi.',anonymizedCustomer:'Cliente anonimizzato',anonymizedHint:'Contatti e note rimossi. Lo storico e i conteggi restano disponibili.',
  privacyTitle:'Informativa privacy',privacyRead:'Leggi l’informativa privacy',privacyAcknowledged:'Ho letto l’informativa privacy per la prenotazione.',marketingOptIn:'Desidero ricevere comunicazioni promozionali dal locale (facoltativo).',allergyWarning:'Se scrivi un’allergia, il locale userà questa informazione solo per gestire la tua richiesta. Evita dettagli sanitari non necessari.',
  privacyDemo:'Informativa dimostrativa: dati e testo del locale devono essere verificati prima dell’uso reale.',privacyController:'Il titolare del trattamento è',privacyProcessor:'BigAnt tratta i dati per conto del locale come responsabile. Non crea un profilo condiviso fra locali.',privacyPurpose:'Nome, email e telefono servono a gestire prenotazione, conferma, disdetta e promemoria, sulla base della richiesta di prenotazione. Non occorre creare un account.',privacyMarketing:'Le promozioni richiedono il consenso facoltativo e separato; puoi revocarlo contattando il locale senza conseguenze sulla prenotazione.',privacySensitive:'Le richieste sono facoltative. Eventuali informazioni sulle allergie sono utilizzate solo per rispondere alla richiesta; non sono incluse nell’export ordinario.',privacyRetention:'I contatti vengono anonimizzati dopo questo numero di mesi senza prenotazioni:',privacyRights:'Per accesso, rettifica, cancellazione, portabilità o revoca del consenso, contatta il locale. Puoi presentare reclamo al Garante per la protezione dei dati personali.',privacyVendors:'Database, immagini, code e log devono risiedere in EU. Prima dell’attivazione il locale verifica i fornitori di consegna e completa questa informativa con destinatari, basi giuridiche e contratti pertinenti.',privacyMissing:'Recapito privacy da configurare prima dell’attivazione.',offlineTitle:'Il pannello richiede una connessione.',offlineHint:'Ricollegati e riapri il tuo locale. I dati degli ospiti non vengono salvati per la consultazione offline.',
 },
 en:{customerDetails:'Guest details',
  notifications:'Notifications',customers:'Guests',notificationTitle:'Keep everyone informed.',notificationHint:'Deliveries and usage for your venue. Uncertain outcomes require verification without automatic resends.',
  demoDelivery:'Local trial: messages are simulated. No email, SMS or push is sent.',liveDelivery:'The service is configured for real messages. Provider acceptance does not mean delivery.',
  queuedMessages:'Queued',simulatedMessages:'Simulated',acceptedMessages:'Accepted by provider',uncertainMessages:'Needs verification',failedMessages:'Not sent',smsUsage:'SMS this month',smsFallback:'Email fallbacks',smsCapHint:'The cap counts messages; charges may depend on segments. Uncertain sends conservatively count towards the cap.',
  smsEnabled:'Enable SMS (Pro/Full plan)',smsCap:'Monthly SMS cap',reminderHours:'Reminder (hours before)',retentionMonths:'Guest retention (months)',privacyContact:'Venue email for privacy and replies',deliveryHistory:'Recent deliveries',noDeliveries:'New bookings will create the first deliveries here.',
  delivery_queued:'Queued',delivery_processing:'Processing',delivery_sent:'Accepted',delivery_failed:'Not sent',delivery_uncertain:'Verify outcome',delivery_simulated:'Simulated',delivery_skipped:'No longer needed',
  event_created:'Booking confirmation',event_pending:'Awaiting confirmation',event_confirmed:'Venue confirmation',event_reminder:'Reminder',event_cancellation:'Cancellation',event_staff_cancellation:'Venue cancellation',event_private_review:'Private feedback',event_new_reservation:'New booking',event_legacy:'History',
  installTitle:'Your venue, always close at hand.',installHint:'On iPhone: Share → Add to Home Screen. On Android use Install in your browser.',installApp:'Install BigAnt',enablePush:'Enable notifications on this device',disablePush:'Disable notifications on this device',pushReady:'Device enabled',pushUnavailable:'Real push requires HTTPS, keys and a configured service. The dashboard remains available.',pushDenied:'Notifications are blocked in browser settings. You can continue using the dashboard.',
  customersTitle:'Your guests.',customersHint:'Private contacts for your venue. The export excludes allergies and free-text notes.',customerSearch:'Find a guest',exportCustomers:'Export CSV',exportedCustomers:'CSV downloaded',noCustomers:'Guests will appear after the first booking.',customerNotes:'Internal guest notes',marketingConsent:'Marketing consent',anonymizeCustomer:'Anonymize guest',anonymizeScheduled:'Anonymizing in 5 seconds.',anonymizedCustomer:'Anonymized guest',anonymizedHint:'Contacts and notes removed. Booking history and counts remain available.',
  privacyTitle:'Privacy notice',privacyRead:'Read the privacy notice',privacyAcknowledged:'I have read the booking privacy notice.',marketingOptIn:'I would like to receive promotions from the venue (optional).',allergyWarning:'If you mention an allergy, the venue will use it only to handle your request. Avoid unnecessary medical details.',
  privacyDemo:'Sample notice: venue details and wording must be verified before real use.',privacyController:'The data controller is',privacyProcessor:'BigAnt processes information on behalf of the venue. It does not create a guest profile shared between venues.',privacyPurpose:'Your name, email and phone are used to handle booking, confirmation, cancellation and reminders on the basis of your booking request. No account is required.',privacyMarketing:'Promotions require optional separate consent. You can withdraw it by contacting the venue without affecting your booking.',privacySensitive:'Requests are optional. Any allergy information is used only to handle the request and excluded from the ordinary export.',privacyRetention:'Contacts are anonymized after this many months without bookings:',privacyRights:'Contact the venue for access, correction, deletion, portability or withdrawal of consent. You may complain to the Italian data protection authority.',privacyVendors:'Databases, images, queues and logs must remain in the EU. Before activation the venue verifies delivery providers and completes this notice with recipients, legal bases and relevant agreements.',privacyMissing:'Privacy contact must be configured before activation.',offlineTitle:'The dashboard needs a connection.',offlineHint:'Reconnect and reopen your venue. Guest information is not saved for offline access.',
 }
} as const;

export const transactionCopy={
 it:{created:'Prenotazione confermata',pending:'Richiesta in attesa di conferma',confirmed:'Il locale ha confermato',reminder:'Ti aspettiamo',cancellation:'Prenotazione disdetta',staff_cancellation:'Il locale ha disdetto la prenotazione',private_review:'Nuovo feedback privato',new_reservation:'Nuova prenotazione',details:'Apri il pannello per i dettagli.',manage:'Gestisci la prenotazione:',guests:'persone',pendingHint:'La richiesta deve ancora essere confermata dal locale.'},
 en:{created:'Booking confirmed',pending:'Request awaiting confirmation',confirmed:'The venue has confirmed',reminder:'See you soon',cancellation:'Booking cancelled',staff_cancellation:'The venue has cancelled the booking',private_review:'New private feedback',new_reservation:'New booking',details:'Open the dashboard for details.',manage:'Manage your booking:',guests:'guests',pendingHint:'The venue still needs to confirm your request.'},
} as const;
