export const roomMessages={
 it:{
  waitingChooseAgain:'Scegli un’alternativa',waitingChoiceChanged:'La disponibilità è cambiata. Scegli di nuovo un tavolo e un orario tra le alternative aggiornate.',
  groupDeactivate:'Disattiva',groupActivate:'Riattiva',tableGroups:'Combinazioni consentite',groupsHint:'Indica quali tavoli si possono unire davvero. L’operatore sceglie la combinazione; il sistema controlla ogni tavolo.',newGroup:'Nuova combinazione',groupName:'Nome combinazione',groupTables:'Tavoli da unire',groupFixed:'Tavoli e capienza restano fissi. Per cambiare struttura crea una nuova combinazione e disattiva questa.',noGroups:'Nessuna combinazione configurata. Puoi continuare con i tavoli singoli.',groupBlocked:'Uno dei tavoli è inattivo o la capienza è cambiata: la combinazione non è assegnabile.',allZones:'Tutte le zone',roomZone:'Filtra per zona',noZone:'Senza zona',waitlist:'Lista d’attesa',waitlistTitle:'Accogli chi aspetta.',waitlistHint:'Una fila per servizio, in ordine di arrivo. Le alternative suggerite aiutano la scelta: decidi tu chi accomodare.',openWaitlist:'Apri lista d’attesa',newWaiting:'Aggiungi in attesa',surname:'Cognome',service:'Servizio',archivedService:'Orario precedente',noWaitlistServices:'Non ci sono servizi per questo giorno. Scegli un altro giorno o controlla gli orari.',noWaiting:'La fila è libera. Aggiungi gli ospiti quando arrivano.',waitingStatus:'In attesa',waitingLeft:'È andato via',waitingSeated:'Accomodato',waitingArrival:'Arrivo',seatWaiting:'Accomoda',waitingCompatible:'C’è una soluzione da valutare',waitingNoFit:'Per ora non c’è un tavolo compatibile. Aggiorniamo le alternative quando si libera posto.',waitingBefore:'Le alternative appariranno all’inizio del servizio.',waitingEnded:'Servizio terminato: lo storico resta qui.',waitingSeatHint:'Scegli una delle alternative. Controlliamo di nuovo tutti i tavoli prima di assegnarli.',waitingSeats:'Posti',waitingPlacement:'Tavolo o combinazione',waitingRefresh:'Aggiorna alternative',waitingLeftScheduled:'Uscita dalla lista in programma',waitingHistory:'Mostra anche accomodati e usciti',groupManual:'Combinazione manuale',waitingNoContacts:'Solo cognome e coperti. Non servono email o telefono e non partono messaggi.',waitingJoined:'Ospite aggiunto alla fila',waitingAssigned:'Ospite accomodato, prenotazione creata',waitingServiceLabel:'Apertura',groupComponents:'Tavoli occupati'
 },
 en:{
  waitingChooseAgain:'Choose an option',waitingChoiceChanged:'Availability has changed. Choose a table and time again from the updated options.',
  groupDeactivate:'Deactivate',groupActivate:'Reactivate',tableGroups:'Allowed combinations',groupsHint:'Specify which tables can actually be joined. Staff chooses the combination; the system checks every table.',newGroup:'New combination',groupName:'Combination name',groupTables:'Tables to join',groupFixed:'Tables and capacity stay fixed. Create a new combination and disable this one to change its structure.',noGroups:'No combinations configured. You can continue using individual tables.',groupBlocked:'A table is inactive or capacity has changed: this combination cannot be assigned.',allZones:'All areas',roomZone:'Filter by area',noZone:'No area',waitlist:'Waiting list',waitlistTitle:'Welcome those waiting.',waitlistHint:'One queue per service, in arrival order. Suggestions help you decide who to seat.',openWaitlist:'Open waiting list',newWaiting:'Add to waiting list',surname:'Surname',service:'Service',archivedService:'Previous opening hours',noWaitlistServices:'There are no services for this day. Choose another day or check opening hours.',noWaiting:'The queue is clear. Add guests when they arrive.',waitingStatus:'Waiting',waitingLeft:'Left',waitingSeated:'Seated',waitingArrival:'Arrived',seatWaiting:'Seat guest',waitingCompatible:'An option is available to consider',waitingNoFit:'There is no suitable table yet. We update alternatives as space becomes available.',waitingBefore:'Options will appear when service starts.',waitingEnded:'Service has ended: its history stays here.',waitingSeatHint:'Choose an option. We check all tables again before assigning them.',waitingSeats:'Seats',waitingPlacement:'Table or combination',waitingRefresh:'Refresh options',waitingLeftScheduled:'Removal from the waiting list scheduled',waitingHistory:'Also show guests seated or who left',groupManual:'Manual combination',waitingNoContacts:'Surname and party size only. No email or phone is needed and no messages are sent.',waitingJoined:'Guest added to the queue',waitingAssigned:'Guest seated, booking created',waitingServiceLabel:'Opening hours',groupComponents:'Occupied tables'
 }
};
